name: ju
version: 1.0.0+1
publish_to: none
description: èšUI
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  dio: ^5.3.3
  flutter_screenutil: ^5.9.0
  flutter_swiper_view: ^1.1.8
  flutter_staggered_grid_view: ^0.7.0
  get: 4.6.6
  multi_select_flutter: ^4.1.3
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.5
  shrine_images: ^2.0.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/diamond.png
    - assets/slanted_menu.png


